# Use postgres/example user/password credentials
version: '3.1'

services:

  database:
      # Official Postgres image from DockerHub (we use the last version)
      image: 'postgres:14.7-alpine3.17'
  
      # By default, a Postgres database is running on the 5432 port.
      # If we want to access the database from our computer (outside the container),
      # we must share the port with our computer's port.
      # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
      # Note: You are free to change your computer's port,
      # but take into consideration that it will change the way
      # you are connecting to your database.
      ports:
        - 5432:5432
  
      environment:
        POSTGRES_USER: debug # The PostgreSQL user (useful to connect to the database)
        POSTGRES_PASSWORD: debug # The PostgreSQL password (useful to connect to the database)
        POSTGRES_DB: hvl_cart # The PostgreSQL default database (automatically created at first launch)
      volumes:
        # In this example, we share the folder `db-data` in our root repository, with the default PostgreSQL data path.
        # It means that every time the repository is modifying the data inside
        # of `/var/lib/postgresql/data/`, automatically the change will appear in `db-data`.
        # You don't need to create the `db-data` folder. Docker Compose will do it for you.
        - ./db-data/:/var/lib/postgresql/data/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
